- hosts: master
  become: yes
  tasks:
    - name: Create an empty file for Kubeadm configuration
      copy:
        content: ""
        dest: /etc/kubernetes/kubeadm-config.yaml
        force: no

    - name: Configure the container runtime and cgroup driver
      blockinfile:
        path: /etc/kubernetes/kubeadm-config.yaml
        block: |
          kind: ClusterConfiguration
          apiVersion: kubeadm.k8s.io/v1beta3
          networking:
            podSubnet: "10.244.0.0/16"
          ---
          kind: KubeletConfiguration
          apiVersion: kubelet.config.k8s.io/v1beta1
          runtimeRequestTimeout: "15m"
          cgroupDriver: "systemd"
          systemReserved:
            cpu: 100m
            memory: 350M
          kubeReserved:
            cpu: 100m
            memory: 50M
          enforceNodeAllocatable:
          - pods

    - name: Initialize the Kubernetes cluster
      shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml >> /home/ubuntu/cluster_initialized.log
      args:
        chdir: /home/ubuntu
        creates: /home/ubuntu/cluster_initialized.log

    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Install Pod network
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> /home/ubuntu/pod_network_setup.log
      args:
        chdir: /home/ubuntu
        creates: /home/ubuntu/pod_network_setup.log
