- hosts: kubernetes_workers
  become: yes
  tasks:
    - name: Ensure TCP port 6443 on master is reachable from worker
      wait_for:
        host: "{{ hostvars['master']['ansible_default_ipv4']['address'] }}"
        port: 6443
        timeout: 30

    - name: Get the join command from master
      shell: kubeadm token create --print-join-command
      register: join_command_raw
      delegate_to: master

    - name: Set join command as fact
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

    - name: Join the cluster
      shell: "{{ join_command }} >> /home/ubuntu/node_joined.log"
      args:
        chdir: /home/ubuntu
        creates: /home/ubuntu/node_joined.log
